entername=input("Enter FirstName")
entername2=input("Enter LastName")
print(f"welcome {entername} {entername2} at Kaikoman")
num=int(input("Enter FirstNumber"))
num2=int(input("Enter LastNumber"))
print(f"The sum of {num} and {num2} is {num+num2}")